//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPR {
	
	
	public partial class BankMaster {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder headPlaceholder;
		
		protected System.Web.UI.WebControls.ImageButton Logo;
		
		protected System.Web.UI.WebControls.Button ContactButton;
		
		protected System.Web.UI.WebControls.Button CurrentUserButton;
		
		protected System.Web.UI.WebControls.Button LogOutButton;
		
		protected System.Web.UI.WebControls.Label BankLabel;
		
		protected System.Web.UI.WebControls.MultiView NavigationBarView;
		
		protected System.Web.UI.WebControls.View AnonView;
		
		protected System.Web.UI.WebControls.TextBox MainSearchbox;
		
		protected System.Web.UI.WebControls.Button SearchButton;
		
		protected System.Web.UI.WebControls.Button ThemeToggle;
		
		protected System.Web.UI.WebControls.View AdminView;
		
		protected System.Web.UI.WebControls.Button Accounts;
		
		protected System.Web.UI.WebControls.Panel MasterContent;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder bodyPlaceholder;
		
		protected System.Web.UI.WebControls.LinkButton AboutButton;
		
		protected System.Web.UI.WebControls.LinkButton ContactUsButton;
		
		protected System.Web.UI.WebControls.LinkButton FollowUsButton;
	}
}
