//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPR {
    
    
    public partial class Default {
        
        protected System.Web.UI.WebControls.Button ClientCreaditRequestButton;
        
        protected System.Web.UI.WebControls.Button ClientContactButton;
        
        protected System.Web.UI.WebControls.GridView ClientCreditGridView;
        
        protected System.Web.UI.WebControls.TextBox CreditRequestFormAmount;
        
        protected System.Web.UI.WebControls.DropDownList CreditRequestFormTerm;
        
        protected System.Web.UI.WebControls.DropDownList CreditRequestFormCurrency;
    }
}
