// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Kickstart {
	
	
	public partial class Profile {
		
		protected System.Web.UI.WebControls.Content ProfileContent;
		
		protected System.Web.UI.WebControls.MultiView GeneralInfoMultiView;
		
		protected System.Web.UI.WebControls.View GeneralInfoView;
		
		protected System.Web.UI.WebControls.Label FullNameLabel;
		
		protected System.Web.UI.WebControls.Label LocationLabel;
		
		protected System.Web.UI.WebControls.Button EditFieldButton;
		
		protected System.Web.UI.WebControls.View GeneralInfoEdit;
		
		protected System.Web.UI.WebControls.TextBox FullName;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.TextBox Phone;
		
		protected System.Web.UI.WebControls.TextBox Country;
		
		protected System.Web.UI.WebControls.TextBox City;
		
		protected System.Web.UI.WebControls.TextBox AddressLine;
		
		protected System.Web.UI.WebControls.Button SaveGeneralInfoButton;
		
		protected System.Web.UI.WebControls.Button Cancel;
		
		protected System.Web.UI.WebControls.MultiView JobSearchInfoMultiView;
		
		protected System.Web.UI.WebControls.View JobSearchView;
		
		protected System.Web.UI.WebControls.Label JobSearchStatusLabel;
		
		protected System.Web.UI.WebControls.Button EditJobStatus;
		
		protected System.Web.UI.WebControls.View JobSearchEdit;
		
		protected System.Web.UI.WebControls.CheckBox LookingForAJobCheckBox;
		
		protected System.Web.UI.WebControls.CheckBox AbleToRelocateCheckBox;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.WebControls.MultiView PersonalStatementMultiView;
		
		protected System.Web.UI.WebControls.View PersonalStatementView;
		
		protected System.Web.UI.WebControls.Label PersonalStatementLabel;
		
		protected System.Web.UI.WebControls.Button Button7;
		
		protected System.Web.UI.WebControls.View PersonalStatementEditView;
		
		protected System.Web.UI.WebControls.TextBox PersonalStatementEdit;
		
		protected System.Web.UI.WebControls.Button Button3;
		
		protected System.Web.UI.WebControls.Button Button4;
		
		protected System.Web.UI.WebControls.MultiView TechnologiesMultiView;
		
		protected System.Web.UI.WebControls.View TechnologiesView;
		
		protected System.Web.UI.WebControls.Label Technologies;
		
		protected System.Web.UI.WebControls.View TechnologiesEditView;
		
		protected System.Web.UI.WebControls.TextBox TechnologiesEdit;
		
		protected System.Web.UI.WebControls.Button Button5;
		
		protected System.Web.UI.WebControls.Button Button6;
		
		protected System.Web.UI.WebControls.Panel ExperiencesPannel;
		
		protected System.Web.UI.WebControls.Button AddExperience;
		
		protected System.Web.UI.WebControls.Panel EducationPannel;
		
		protected System.Web.UI.WebControls.Button AddEducation;
	}
}
