// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Kickstart {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl LoginDialog;
		
		protected System.Web.UI.HtmlControls.HtmlForm LoginForm;
		
		protected System.Web.UI.WebControls.MultiView LoginFormMultiView;
		
		protected System.Web.UI.WebControls.View EmailPasswordRegistrationView;
		
		protected System.Web.UI.WebControls.Label EmailLabel;
		
		protected System.Web.UI.WebControls.TextBox EmailField;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator EmailFieldRegExpValidator;
		
		protected System.Web.UI.WebControls.Label PasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox PasswordField;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator PasswordFieldRegExpValidator;
		
		protected System.Web.UI.WebControls.CheckBox RememberCheckBox;
		
		protected System.Web.UI.WebControls.Panel AccountButtonsPannel;
		
		protected System.Web.UI.WebControls.Button RegisterButton;
		
		protected System.Web.UI.WebControls.Button LoginButton;
		
		protected System.Web.UI.WebControls.LinkButton ForgetPasswordLinkButton;
		
		protected System.Web.UI.WebControls.View ContinueRegistrationView;
		
		protected System.Web.UI.WebControls.Panel AccountTypeSelectionPannel;
		
		protected System.Web.UI.WebControls.DropDownList AcountTypeDropdownList;
		
		protected System.Web.UI.WebControls.Label RegistartionStatusLabel;
		
		protected System.Web.UI.WebControls.Button ConfirmRegistrationButton;
		
		protected System.Web.UI.WebControls.Button CancelRegistrationButton;
		
		protected System.Web.UI.WebControls.Label LoginStatus;
	}
}
