// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Kickstart {
	
	
	public partial class Kickstart {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder headPlaceholder;
		
		protected System.Web.UI.WebControls.Label AccountLabel;
		
		protected System.Web.UI.WebControls.Button LogOutButton;
		
		protected System.Web.UI.WebControls.ImageButton Logo;
		
		protected System.Web.UI.WebControls.MultiView NavigationBarView;
		
		protected System.Web.UI.WebControls.View DeveloperView;
		
		protected System.Web.UI.WebControls.Button HomeButton;
		
		protected System.Web.UI.WebControls.Button SearchJobsButton;
		
		protected System.Web.UI.WebControls.Button MyProfileButton;
		
		protected System.Web.UI.WebControls.View AdminView;
		
		protected System.Web.UI.WebControls.Button Accounts;
		
		protected System.Web.UI.WebControls.Button Companies;
		
		protected System.Web.UI.WebControls.Button CVs;
		
		protected System.Web.UI.WebControls.Button Educations;
		
		protected System.Web.UI.WebControls.Button Experiences;
		
		protected System.Web.UI.WebControls.Button Locations;
		
		protected System.Web.UI.WebControls.Button Roles;
		
		protected System.Web.UI.WebControls.Button Technologies;
		
		protected System.Web.UI.WebControls.Button Vacancies;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder;
		
		protected System.Web.UI.WebControls.LinkButton AboutButton;
		
		protected System.Web.UI.WebControls.LinkButton BlogButton;
		
		protected System.Web.UI.WebControls.LinkButton ContactUsButton;
		
		protected System.Web.UI.WebControls.LinkButton FollowUsButton;
		
		protected System.Web.UI.WebControls.Label Copyright;
	}
}
