//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1 {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content DefaultContent;
		
		protected System.Web.UI.WebControls.MultiView DefaultPageMultiView;
		
		protected System.Web.UI.WebControls.View DefaultPageAnonView;
		
		protected System.Web.UI.WebControls.TextBox RegisterUsername;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RegisterUsernameValidator;
		
		protected System.Web.UI.WebControls.TextBox RegisterEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RegisterEmailValidator;
		
		protected System.Web.UI.WebControls.TextBox RegisterPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RegisterPasswordValidor;
		
		protected System.Web.UI.WebControls.CheckBox RegisterAcceptsTerms;
		
		protected System.Web.UI.WebControls.Button RegisterButton;
		
		protected System.Web.UI.WebControls.View DefaultPageMemberView;
		
		protected System.Web.UI.WebControls.Label DefaultPageMemberViewGreeting;
		
		protected System.Web.UI.WebControls.Label DefaultSearchReqest;
		
		protected System.Web.UI.WebControls.DataList DefaultPageRecordList;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl DefaultPageRecordListItem;
		
		protected System.Web.UI.WebControls.ImageButton DefaultPageRecordListItemImage;
		
		protected System.Web.UI.WebControls.Label DefaultPageRecordListItemTitle;
		
		protected System.Web.UI.WebControls.Label DefaultPageRecordListItemArtist;
	}
}
