//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1 {
    
    
    public partial class MusicdropMaster {
        
        protected System.Web.UI.WebControls.ContentPlaceHolder headPlaceholder;
        
        protected System.Web.UI.WebControls.ImageButton Logo;
        
        protected System.Web.UI.WebControls.MultiView TopBarMultiView;
        
        protected System.Web.UI.WebControls.View MasterUnloggedView;
        
        protected System.Web.UI.WebControls.TextBox MasterLoginEmail;
        
        protected System.Web.UI.WebControls.TextBox MasterLoginPassword;
        
        protected System.Web.UI.WebControls.Button MasterLoginButton;
        
        protected System.Web.UI.WebControls.View MasterLoggedView;
        
        protected System.Web.UI.WebControls.Button MasterLoggedViewCurrentUser;
        
        protected System.Web.UI.WebControls.Button MasterLoggedViewLogOutButton;
        
        protected System.Web.UI.WebControls.Label MusicdropLabel;
        
        protected System.Web.UI.WebControls.TextBox MainSearchbox;
        
        protected System.Web.UI.WebControls.Button MasterSearchButton;
        
        protected System.Web.UI.WebControls.DropDownList MasterSearchDropdown;
        
        protected System.Web.UI.WebControls.Button ThemeToggle;
        
        protected System.Web.UI.WebControls.Button MainButon;
        
        protected System.Web.UI.WebControls.MultiView NavigationBarView;
        
        protected System.Web.UI.WebControls.View AnonView;
        
        protected System.Web.UI.WebControls.View MemeberView;
        
        protected System.Web.UI.WebControls.Button Dashboard;
        
        protected System.Web.UI.WebControls.Button AddRecord;
        
        protected System.Web.UI.WebControls.Panel MasterContent;
        
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder;
        
        protected System.Web.UI.WebControls.LinkButton AboutButton;
        
        protected System.Web.UI.WebControls.LinkButton API;
        
        protected System.Web.UI.WebControls.LinkButton BlogButton;
        
        protected System.Web.UI.WebControls.LinkButton ContactUsButton;
        
        protected System.Web.UI.WebControls.LinkButton FollowUsButton;
    }
}
