//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1 {
	
	
	public partial class Profile {
		
		protected System.Web.UI.WebControls.Content ProfileContent;
		
		protected System.Web.UI.WebControls.Label ProfileId;
		
		protected System.Web.UI.WebControls.Label ProfileName;
		
		protected System.Web.UI.WebControls.Label ProfileEmail;
	}
}
