//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1 {
    
    
    public partial class Record {
        
        protected System.Web.UI.WebControls.Content RecordContent;
        
        protected System.Web.UI.WebControls.MultiView RecordMultiView;
        
        protected System.Web.UI.WebControls.View RecordViewForm;
        
        protected System.Web.UI.WebControls.Label ViewRecordId;
        
        protected System.Web.UI.WebControls.Button ViewRecordEditButton;
        
        protected System.Web.UI.WebControls.Label ViewRecordRating;
        
        protected System.Web.UI.WebControls.Button ViewRecordUp;
        
        protected System.Web.UI.WebControls.Button ViewRecordDown;
        
        protected System.Web.UI.WebControls.ImageButton ViewRecordCover;
        
        protected System.Web.UI.WebControls.Label ViewRecordArtist;
        
        protected System.Web.UI.WebControls.Label ViewRecordTitle;
        
        protected System.Web.UI.WebControls.Label ViewRecordLabel;
        
        protected System.Web.UI.WebControls.Label ViewRecordGenre;
        
        protected System.Web.UI.WebControls.Label ViewRecordStyle;
        
        protected System.Web.UI.WebControls.Label ViewRecordFormat;
        
        protected System.Web.UI.WebControls.Label ViewRecordContry;
        
        protected System.Web.UI.WebControls.View RecordEditView;
        
        protected System.Web.UI.WebControls.Label EditRecordId;
        
        protected System.Web.UI.WebControls.FileUpload EditRecordFileUpload;
        
        protected System.Web.UI.WebControls.Button EditRecordFileUploadButton;
        
        protected System.Web.UI.WebControls.Label EditRecordFileUploadStatus;
        
        protected System.Web.UI.WebControls.ImageButton EditRecordCover;
        
        protected System.Web.UI.WebControls.TextBox EditRecordTitle;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator EditRecordUsernameValidator;
        
        protected System.Web.UI.WebControls.TextBox EditRecordArtist;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator EditRecordArtistValidator;
        
        protected System.Web.UI.WebControls.TextBox EditRecordLabel;
        
        protected System.Web.UI.WebControls.RequiredFieldValidator EditRecordLabelValidator;
        
        protected System.Web.UI.WebControls.TextBox EditRecordYear;
        
        protected System.Web.UI.WebControls.TextBox EditRecordOther;
        
        protected System.Web.UI.WebControls.DropDownList EditRecordGenre;
        
        protected System.Web.UI.WebControls.DropDownList EditRecordStyle;
        
        protected System.Web.UI.WebControls.DropDownList EditRecordFormat;
        
        protected System.Web.UI.WebControls.DropDownList EditRecordCountry;
        
        protected System.Web.UI.WebControls.Panel EditRecordTracksPanel;
        
        protected System.Web.UI.WebControls.RangeValidator EditRecordTrackCountValidator;
        
        protected System.Web.UI.WebControls.TextBox EditRecordTrackCount;
        
        protected System.Web.UI.WebControls.Button EditRecordAddTrack;
        
        protected System.Web.UI.WebControls.Button EditRecordButton;
        
        protected System.Web.UI.WebControls.Button ResetRecordButton;
        
        protected System.Web.UI.WebControls.Button DeleteRecordButton;
    }
}
